
SET(MODULES_EXTERNAL_DIR ${CMAKE_CURRENT_SOURCE_DIR}/External)

ADD_SUBDIRECTORY(${MODULES_EXTERNAL_DIR}/IOCore)
ADD_SUBDIRECTORY(${MODULES_EXTERNAL_DIR}/QJsonModel)

# Add ${MODULES_EXTERNAL_DIR} modules to the C++ include search path
INCLUDE_DIRECTORIES(${MODULES_EXTERNAL_DIR})

ADD_SUBDIRECTORY(elemental)
ADD_SUBDIRECTORY(EditorWidgets)

