#!/bin/sh

# Ensure Homebrew's LLVM is installed
if ! brew list llvm &>/dev/null; then
	echo "LLVM is not installed via Homebrew. Installing..."
	brew install llvm
fi
# Detect the path to the currently active macOS SDK
export CMAKE_OSX_SYSROOT=$(xcrun --sdk macosx --show-sdk-path)

# Determine the Homebrew prefix
BREW_PREFIX=$(brew --prefix)

export PATH="${BREW_PREFIX}/opt/llvm/bin:${PATH}"

export CMAKE_C_COMPILER=${CMAKE_C_COMPILER:-"clang"}
export CMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER:-"clang++"}



# Set environment variables for compilers

# Set flags for linker and compiler to use Homebrew's LLVM
#  You don't want to uncomment this unless you know what you're doing
#export LDFLAGS="-L${BREW_PREFIX}/opt/llvm/lib -Wl,-rpath,${BREW_PREFIX/}opt/llvm/lib"
#export LDFLAGS="${LDFLAGS} -L${BREW_PREFIX}/opt/llvm/lib/c++ -L${BREW_PREFIX}/opt/llvm/lib/unwind"
#
#export CXXFLAGS="-I${BREW_PREFIX}/opt/llvm/include"
# Set SDKROOT to ensure compatibility with macOS SDK
#export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)

# Inform the user
echo "Environment configured to use Homebrew's LLVM/Clang with CMake."

# vim: set ts=4 sw=4 noet:
