CMAKE_MINIMUM_REQUIRED(VERSION 3.26)

# Additional paths to search for custom and third-party CMake modules
LIST(PREPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/CMake)

INCLUDE(DefaultConfig)

INCLUDE(BuildOptions)
INCLUDE(BuildProperties)

PROJECT(Elemental
	VERSION 0.0.6
	LANGUAGES C CXX
	# Save this for later:
	# HOMEPAGE_URL <URL>
	DESCRIPTION "A simple top-down strategy game"
)

INCLUDE(CPM)

SET(${PROJECT_NAME}_CMAKE_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})

OPTION(CI_BUILD
	"Mark this as a CI/CD system build."
)

IF(CI_BUILD)
	ADD_COMPILE_DEFINITIONS(-DCI_BUILD=1)
ENDIF()

# enable compile_commands.json generation for clangd
SET(CMAKE_EXPORT_COMPILE_COMMANDS On)

IF(NOT CMAKE_BUILD_TYPE)
	SET( CMAKE_BUILD_TYPE Debug )
ENDIF()

SET(CMAKE_C_STANDARD 17)
SET(CMAKE_CXX_STANDARD 20)

# Disable GNU compiler extensions
SET(CMAKE_C_EXTENSIONS OFF)
SET(CMAKE_CXX_EXTENSIONS OFF)

CPMFindPackage(NAME span-lite
	GITHUB_REPOSITORY martinmoene/span-lite
	GIT_TAG v0.11.0
	OPTIONS
		"SPAN_LITE_OPT_BUILD_TESTS OFF"
		"SPAN_LITE_OPT_BUILD_EXAMPLES OFF"
)

FIND_PACKAGE(Fontconfig REQUIRED)

IF(BUILD_TESTING)

	CPMFindPackage(NAME Catch2
		GITHUB_REPOSITORY catchorg/Catch2
		VERSION 3.6.0
		OPTIONS "CATCH_DEVELOPMENT_BUILD OFF" "CATCH_BUILD_TESTING OFF"
	)

	CPMFindPackage(NAME FakeIt
		GITHUB_REPOSITORY eranpeer/FakeIt
		GIT_TAG 2.4.1
		OPTIONS
		"BUILD_TESTING OFF"
	)

	IF(TARGET Catch2)
		set_target_properties(Catch2 PROPERTIES
			CXX_STANDARD 20
		)
	endif()
	IF(TARGET Catch2WithMain)
		set_target_properties(Catch2WithMain PROPERTIES
 			CXX_STANDARD 20
		)
	endif()

	IF(Catch2_ADDED)
		list(APPEND CMAKE_MODULE_PATH ${Catch2_SOURCE_DIR}/extras)
	else()
		IF(Catch2_DIR)
			list(APPEND CMAKE_MODULE_PATH ${Catch2_DIR})
		endif()
	endif()
endif()

CPMFindPackage(
	NAME fmt
	URL https://github.com/fmtlib/fmt/archive/refs/tags/10.2.1.zip
	URL_HASH SHA256=d368f9c39a33a3aef800f5be372ec1df1c12ad57ada1f60adc62f24c0e348469
)
FIND_PACKAGE(Qt6 COMPONENTS
	Core REQUIRED
	Widgets REQUIRED
	Gui REQUIRED
)
SET(CMAKE_AUTOMOC OFF)
SET(CMAKE_AUTOUIC OFF)

qt_standard_project_setup()

# Set output directories for build targets
set_artifact_dir(${CMAKE_BINARY_DIR}/out)

# Initialize FetchContent
INCLUDE(FetchContent)
INCLUDE(CheckIncludeFile)

# Initialize pkgconf
FIND_PACKAGE(Threads)  # POSIX thread support
FIND_PACKAGE(PkgConfig REQUIRED)

# TODO: Switch this to CPM Package manager

# Example: Find SDL2, SDL2_image, and SDL2_gfx using PkgConfig
# add IMPORTED_TARGET to enable fancy PkgConfig::SDL2 syntax
pkg_check_modules(SDL2 REQUIRED IMPORTED_TARGET sdl2)
pkg_check_modules(SDL2_IMAGE REQUIRED IMPORTED_TARGET SDL2_image)
pkg_check_modules(SDL2_GFX REQUIRED IMPORTED_TARGET SDL2_gfx)
pkg_check_modules(SDL2_TTF REQUIRED IMPORTED_TARGET SDL2_ttf)

SET(SDL2_COMBINED_INCLUDE_DIRS "")
LIST(APPEND SDL2_COMBINED_INCLUDE_DIRS ${SDL2_INCLUDE_DIRS})
LIST(APPEND SDL2_COMBINED_INCLUDE_DIRS ${SDL2_IMAGE_INCLUDE_DIRS})
LIST(APPEND SDL2_COMBINED_INCLUDE_DIRS ${SDL2_GFX_INCLUDE_DIRS})
LIST(APPEND SDL2_COMBINED_INCLUDE_DIRS ${SDL2_TTF_INCLUDE_DIRS})
LIST(REMOVE_DUPLICATES SDL2_COMBINED_INCLUDE_DIRS)

INCLUDE_DIRECTORIES(SYSTEM ${SDL2_COMBINED_INCLUDE_DIRS})

SET(SDL2_COMBINED_LINK_DEPS
	PkgConfig::SDL2
	PkgConfig::SDL2_IMAGE
	PkgConfig::SDL2_GFX
	PkgConfig::SDL2_TTF
)

IF(CMAKE_BUILD_TYPE STREQUAL "Debug")
	ADD_COMPILE_DEFINITIONS(-DDEBUG=1)
ENDIF()

# Add subdirectories
ADD_SUBDIRECTORY(Modules)
INCLUDE_DIRECTORIES(BEFORE ${Elemental_CMAKE_SOURCE_DIR}/Modules)

IF(BUILD_TESTING)
	ADD_SUBDIRECTORY(Tests)
ENDIF()

ADD_SUBDIRECTORY(Apps)

# vim: ts=4 sw=4 noet foldmethod=indent :
